version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:server


  api:
    container_name: api
    restart: always
    build: ./strava-oauth
    ports:
      - "5042:5042"
    command: python api.py


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app
      - api