version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    environment:
      - APP_URL=http://test.velometria.com
    ports:
      - "8000:8000"
    command: gunicorn -w 2 -b :8000 app:server


  api:
    container_name: api
    restart: always
    build: ./strava-oauth
    environment:
      - APP_URL=http://test.velometria.com
    env_file: 
      - .env
    ports:
      - "5042:5042"
    volumes:
      - stravadata:/root/.stravadata
    command: python api.py


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app
      - api

volumes:
  stravadata: